name: unit-tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run Spanner emulator
        run: docker run -d -p 9010:9010 -p 9020:9020 gcr.io/cloud-spanner-emulator/emulator

      - name: Run golint
        run: golint ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -timeout 2m -v ./...